sonar.projectKey=govuk-once_govuk-mobile-ios-app
sonar.projectName=govuk-mobile-ios-app
sonar.pullrequest.github.repository=govuk-once/govuk-mobile-ios-app

sonar.organization=govuk-once

sonar.sources=Production
sonar.exclusions=Production/govuk_ios/Extensions/Resolver/Resolver+*.swift, Production/govuk_ios_notification_service/**, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/**/*.png
sonar.coverage.exclusions=Production/govuk_ios/SupportingFiles/**,Production/govuk_ios/Views/Home/AlertBannerWidgetView.swift, Production/govuk_ios/Views/Home/UserFeedbackWidgetView.swift, Production/govuk_ios/Views/Chat/ChatWidgetView.swift,Production/govuk_ios/Services/AppAttest/GovUKProviderFactory.swift
sonar.cpd.exclusions=Production/govuk_ios/Extensions/Onboarding/OnboardingSlides+Convenience.swift
sonar.tests=Tests

sonar.language=swift
sonar.sourceEncoding=UTF-8
sonar.pullrequest.provider=github

sonar.host.url=https://sonarcloud.io
